In [1]:
import numpy as np
import pandas as pd


In [25]:
docs = ["portal vein is not dileted","liver surface is quite wavey",
        "liver size is notmal","urinary bladder is normal"]

In [3]:
from string import punctuation
from nltk.corpus import stopwords
 

In [7]:
from sklearn.feature_extraction.text import CountVectorizer

In [8]:
corpus = [
     'This is the first document.',
     'This document is the second document.',
     'And this is the third one.',
     'Is this the first document?',
 ]

In [9]:
vectorizer = CountVectorizer()

In [26]:
X = vectorizer.fit_transform(docs)

In [27]:
print(vectorizer.get_feature_names())

['bladder', 'dileted', 'is', 'liver', 'normal', 'not', 'notmal', 'portal', 'quite', 'size', 'surface', 'urinary', 'vein', 'wavey']


In [28]:
print(X.toarray())

[[0 1 1 0 0 1 0 1 0 0 0 0 1 0]
 [0 0 1 1 0 0 0 0 1 0 1 0 0 1]
 [0 0 1 1 0 0 1 0 0 1 0 0 0 0]
 [1 0 1 0 1 0 0 0 0 0 0 1 0 0]]


In [29]:
from sklearn.neighbors import KNeighborsClassifier

In [30]:
y = [0, 0, 1, 1]

In [31]:
neigh = KNeighborsClassifier(n_neighbors=3)
model = neigh.fit(X, y) 

In [32]:
print(model.predict(X))

[1 1 1 1]
